### PR TITLE
GitHub action to run integration tests

### PR DESCRIPTION
**Pull request by tdddblog**
See https://github.com/NASA-PDS/pds-registry-app/issues/154

### CODE REVIEW

**Comment by tdddblog** [comment]
🤪 Unstable integration & delivery failed because of wrong JDK version. JDK 11 is required to build registry manager and harvest.

**Comment by jordanpadams** [comment]
@tdddblog you can specify that in the roundup action. see https://github.com/NASA-PDS/validate/blob/master/.github/workflows/unstable-cicd.yaml#L61

**Comment by jordanpadams** [comment]
also looks like it is in the roundup docs too: https://github.com/NASA-PDS/roundup-action/#-pds-engineering-actions-roundup

**Comment by tdddblog** [comment]
I fixed JDK issue, but now roundup action is failing with some other git related error.

**Pull request merged**
