### PR TITLE
Update product's archive status

### PR DESCRIPTION
**Pull request by tdddblog**
## 🗒️ Summary
(1) Update product's archive status - individual products, collections and primary references, bundles. (Issues 2, 8, 12)
(2) Skip bad files (Issue 75)

## ⚙️ Test Data and/or Report
(1) Update archive status story
- Harvest any file(s).
- Check `registry-docs.json` in the output folder. Each product should have the following field:
`"ops:Tracking_Meta/ops:archive_status":"staged"`

(2)  Skip bad files
Follow instructions in https://github.com/NASA-PDS/harvest/issues/75

NOTE: Most of the changes in this commit is a refactoring of old command-line tools and web services ("big data") projects to eliminate duplicate code. The common code was moved to "registry-commons" project.

## ♻️ Related Issues
(1)
https://github.com/NASA-PDS/registry-harvest-cli/issues/2
https://github.com/nasa-pds/registry-harvest-service/issues/12
https://github.com/NASA-PDS/registry-harvest-cli/issues/8
(2)
https://github.com/NASA-PDS/harvest/issues/75

### CODE REVIEW

**Comment by tloubrieu-jpl** [comment]
Hi @tdddblog , can you give some guidelines on how to use set the archive status ? Is it in the configuration ? I don't see the option in the command line arguments.

**Comment by tdddblog** [comment]
@tloubrieu-jpl I updated test instructions for both harvest and registry manager.

**Comment by tloubrieu-jpl** [comment]
Thanks @tdddblog  So all the files are alway imported in a 'staged' status ?

**Review by tloubrieu-jpl — APPROVED** [review]
good to go, thanks @tdddblog

**Comment by tdddblog** [comment]
@tloubrieu-jpl Yes. That's the requirement described in "Public vs Private Data" slides.

**Pull request merged**
