### PR TITLE
changes for common log4j

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Updated to latest log4j pattern.

## ⚙️ Test Data and/or Report
Log now looks like:
```
2024-11-14 10:24:50 [INFO ] (FileDownloader.java:download:79) 404 - Not Found
2024-11-14 10:24:50 [INFO ] (FileDownloader.java:download:82) Will retry in 5 seconds
2024-11-14 10:24:55 [INFO ] (FileDownloader.java:downloadOnce:106) Downloading https://pds.nasa.gov/pds4/mission/insight/v1/PDS4_INSIGHT_1A10_1830.JSON to /tmp/LDD-17278595985076089148.JSON
```

## ♻️ Related Issues
Partial #203

### CODE REVIEW

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @alexdunnjpl @nutjob4life can we get a review on this? it is getting a bit stale.

**Review by alexdunnjpl — APPROVED** [review]
Possibly this is worth throwing in a constant somewhere if it's in use across the codebase?

But either way, approved

**Comment by nutjob4life** [comment]
@alexdunnjpl beat me to it—but I'd also approve based on visual inspection

**Comment by jordanpadams** [comment]
thanks @alexdunnjpl @nutjob4life !

**Comment by jordanpadams** [comment]
agreed on the global constant in registry common, but let's move this forward.

**Pull request merged**
