### PR TITLE
New feature to allow harvest to set archive status

### LINKED ISSUE #135: As a user, I want the default archive_status for loaded products to be configurable
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data operators in the discipline nodes.

### 💪 Motivation

...so that I can skip the staged status (when metadata comes from a validated database) and make the product directly available to the public.

### 📖 Additional Details

_No response_

### Acceptance Criteria

**Given** a bundle
**When I perform** harvest on it with an option `--archive-status archived`
**Then I expect** the products of this bundles to all have the archive-status `archived`.

**Given** a bundle
**When I perform** harvest on it **without** option `--archive-status archived`
**Then I expect** the products of this bundles to all have the archive-status `staged`.

### ⚙️ Engineering Details

_No response_

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Allow harvest to define the archive status when it harvests the data.

## ⚙️ Test Data and/or Report
Validated by setting to certified and looked in DB. Also tried with fred and it failed giving a list of valid choices.

## ♻️ Related Issues
Closes #135 
Requires NASA-PDS/registry-common#56

### CODE REVIEW

**Comment by jordanpadams** [comment]
@al-niessner is there any kind of integration tests we could add to the our registry test suite to verify the setting of archive status upon loading of the data?

**Comment by al-niessner** [comment]
@jordanpadams 

We could add a trivial test that show that the default variable is updated. Not sure that does much but could offer a very modest amount of regression. Otherwise back to needing a running opensearch, secrets, test data, expectations that change with the data etc.

**Comment by jordanpadams** [comment]
@al-niessner thanks. I don’t think a test like that is necessary worth it. I will try to test this over the weekend.

**Comment by tloubrieu-jpl** [comment]
@al-niessner @jordanpadams, I suspect we will encounter the same issue that we are having on https://github.com/NASA-PDS/registry-mgr/pull/82#issuecomment-2276567447

But for now I am having a different issue:

```
% ./bin/registry-manager set-archive-status \
    -auth /Users/loubrieu/Documents/pds/registry/es-auth.txt \
    -es file:/Users/loubrieu/Documents/pds/registry/mcp_dev.xml \
    -packageId 8d12a9ba-2ba0-4d80-8ce9-65da271ecf89 \
    -status archived

[ERROR] Missing required parameter '-lidvid' or '-packageId
```

@al-niessner is that something you can reproduce ?

Thanks

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

This is about harvest not registry-mgr. Not sure if something is wrong in your environment or just putting messages in different PRs.

**Comment by tloubrieu-jpl** [comment]
Sorry @al-niessner, I was confused about what the PR was for. I will test that again, more appropriately.

**Comment by tloubrieu-jpl** [comment]
I was finally able to validate that new development by manual test on MCP Dev account.

**Review by tloubrieu-jpl — APPROVED** [review]
That works perfectly on MCP Dev.

Thanks @al-niessner

**Pull request merged**
